[package]
name = "nirrpe_launcher"
version = "0.1.0"
edition = "2021"
authors = [
    "Arc-blroth <45273859+Arc-blroth@users.noreply.github.com>",
    "MaowImpl <aidancrafter@gmail.com>"
]

[dependencies]
